export const content = {
    en: {
      home: "Home",
      question: "Question",
      score: "Score",
      bestOfLuck: "Best of luck for your quiz!",
      startQuiz: "Start Quiz",
      nextQuestion: "Next Question",
      submit: "Submit",
      playAgain: "Play Again",
      quizComplete: "Quiz Complete!",
      showHint: "Show Hint",
      hideHint: "Hide Hint",
      welcomeMessage: "Welcome to the Computer Quiz! Enter your name to begin.",
      nameLabel: "Your Name",
      nameRequired: "Please enter your name to start the quiz.",
      timesUp: "Time's Up!",
      results: {
        failed: "Failed",
        passed: "Passed",
        c_grade: "Grade: C",
        b_grade: "Grade: B",
        a_grade: "Grade: A",
        excellent: "Excellent!",
        failedMessage: "Don't worry, {studentName}. Every expert was once a beginner. Keep trying!",
        passedMessage: "Good job, {studentName}! You've passed the quiz.",
        c_gradeMessage: "Nice work, {studentName}! You're getting the hang of it.",
        b_gradeMessage: "Great job, {studentName}! You have a solid understanding.",
        a_gradeMessage: "Excellent work, {studentName}! You're a star!",
        excellentMessage: "Outstanding, {studentName}! You're a computer whiz!",
      },
      quizData: [
        {
          id: "q1",
          question: "If you are drawing a picture on a computer, which device are you using to get your drawing from your hand into the computer?",
          options: [
            { text: "Monitor", isCorrect: false, rationale: "A monitor shows you the picture (output), but doesn't let you draw it into the computer." },
            { text: "Printer", isCorrect: false, rationale: "A printer takes the picture from the computer and puts it on paper (output)." },
            { text: "Mouse or Drawing Tablet", isCorrect: true, rationale: "A mouse or a special drawing tablet are used to send your hand movements into the computer (input)." },
            { text: "Speakers", isCorrect: false, rationale: "Speakers are for sound (output), not for drawing." },
          ],
          hint: "Think about which device lets you 'put' information into the computer.",
        },
        {
          id: "q2",
          question: "A baker uses a recipe to know how much flour and sugar to add. In a computer, what part acts like the recipe, telling all the other parts what to do?",
          options: [
            { text: "The Monitor", isCorrect: false, rationale: "The monitor just shows the result, like a decorated cake. It doesn't give the instructions." },
            { text: "The Control Unit (CU)", isCorrect: true, rationale: "The Control Unit (CU) directs the flow of data and instructions, just like a recipe guides the baker." },
            { text: "The Hard Drive", isCorrect: false, rationale: "The hard drive is like the pantry where you store ingredients (data) for later, not the recipe itself." },
            { text: "The Power Supply", isCorrect: false, rationale: "The power supply provides energy, like the oven's heat, but doesn't give instructions." },
          ],
          hint: "Which part of the CPU is the 'director' or 'manager'?",
        },
        {
          id: "q3",
          question: "You need to do your math homework which has many addition and subtraction problems. Which part of the CPU is like a calculator that will do all the math for you?",
          options: [
            { text: "RAM", isCorrect: false, rationale: "RAM is like your workbench, holding the homework (data) temporarily, but it doesn't do the calculations." },
            { text: "The Control Unit (CU)", isCorrect: false, rationale: "The Control Unit tells the computer *what* to do, but it doesn't do the math itself." },
            { text: "Arithmetic Logic Unit (ALU)", isCorrect: true, rationale: "The ALU is the part of the CPU that performs all arithmetic (like addition) and logical operations." },
            { text: "The Keyboard", isCorrect: false, rationale: "The keyboard is used to type the numbers in (input), not to calculate them." },
          ],
          hint: "Which part of the CPU has 'Arithmetic' in its name?",
        },
        {
          id: "q4",
          question: "Your friend wants to listen to a song you have on your computer. How does the computer send the sound out for your friend to hear?",
          options: [
            { text: "Through the Keyboard", isCorrect: false, rationale: "A keyboard is for putting information in, not getting sound out." },
            { text: "Through the Speakers", isCorrect: true, rationale: "Speakers are output devices specifically designed to turn electrical signals into sound." },
            { text: "Through the Mouse", isCorrect: false, rationale: "A mouse is for controlling the cursor and clicking (input)." },
            { text: "Through the CPU", isCorrect: false, rationale: "The CPU processes the song file, but it doesn't produce the sound you hear." },
          ],
          hint: "Which device makes noise?",
        },
        {
          id: "q5",
          question: "Imagine the CPU's Control Unit is a traffic cop. What is its main job in the computer?",
          options: [
            { text: "Doing all the math problems.", isCorrect: false, rationale: "That's the job of the ALU (Arithmetic Logic Unit), which is like a super-fast calculator." },
            { text: "Storing all your games and photos.", isCorrect: false, rationale: "That's the job of the Hard Drive or SSD, which is the long-term storage." },
            { text: "Directing the flow of information between all parts of the computer.", isCorrect: true, rationale: "Just like a traffic cop, the CU directs where data should go, ensuring everything happens in the right order." },
            { text: "Showing pictures on the screen.", isCorrect: false, rationale: "That's the job of the graphics card and the monitor." },
          ],
          hint: "A traffic cop manages movement and direction.",
        },
        {
          id: "q6",
          question: "You are playing a video game and you press the 'jump' button. This action is an example of:",
          options: [
            { text: "Input", isCorrect: true, rationale: "You are sending a command *into* the computer, telling your character to jump." },
            { text: "Output", isCorrect: false, rationale: "The character jumping on the screen is the output. Pressing the button is the input." },
            { text: "Storage", isCorrect: false, rationale: "Storage is for saving the game so you can play it later." },
            { text: "Processing", isCorrect: false, rationale: "The CPU processing the jump command is the processing step, which happens after your input." },
          ],
          hint: "Are you telling the computer something, or is it telling you something?",
        },
        {
          id: "q7",
          question: "Which of the following is NOT a piece of computer hardware?",
          options: [
            { text: "The CPU chip", isCorrect: false, rationale: "The CPU is a physical chip, so it is hardware." },
            { text: "The RAM sticks", isCorrect: false, rationale: "RAM sticks are physical circuit boards, so they are hardware." },
            { text: "The video game you are playing", isCorrect: true, rationale: "A video game is a program, which is software. You can't physically touch the game itself." },
            { text: "The computer mouse", isCorrect: false, rationale: "The mouse is a physical device you can hold, so it is hardware." },
          ],
          hint: "Hardware is the physical parts of a computer that you can touch.",
        },
        {
          id: "q8",
          question: "If you want to save a drawing you made so you can show it to your family tomorrow, where should the computer put it?",
          options: [
            { text: "In RAM", isCorrect: false, rationale: "RAM is temporary memory, like a whiteboard. It gets erased when you turn the computer off." },
            { text: "On the Hard Drive", isCorrect: true, rationale: "The hard drive is for long-term storage. Files saved there will stay even after the computer is shut down." },
            { text: "On the Monitor", isCorrect: false, rationale: "The monitor only displays the drawing; it doesn't save it." },
            { text: "In the CPU", isCorrect: false, rationale: "The CPU processes the drawing, but it doesn't store it for long periods." },
          ],
          hint: "Which part is used for permanent, long-term saving?",
        },
        {
          id: "q9",
          question: "The CPU is the 'brain' of the computer. It is made of two main parts that work together. What are they?",
          options: [
            { text: "The Keyboard and Mouse", isCorrect: false, rationale: "The keyboard and mouse are input devices, separate from the CPU." },
            { text: "RAM and Hard Drive", isCorrect: false, rationale: "RAM and the hard drive are types of memory/storage, not the core processing parts of the CPU." },
            { text: "The Control Unit (CU) and Arithmetic Logic Unit (ALU)", isCorrect: true, rationale: "The CU directs tasks and the ALU performs calculations. Together, they form the core of the CPU." },
            { text: "The Monitor and Speakers", isCorrect: false, rationale: "The monitor and speakers are output devices." },
          ],
          hint: "One part is the 'director' and the other is the 'calculator'.",
        },
        {
          id: "q10",
          question: "You're writing a school report. You press a letter on the keyboard. What is the keyboard's job in this process?",
          options: [
            { text: "To show the letter on the screen.", isCorrect: false, rationale: "That's the monitor's job (output)." },
            { text: "To send the letter's signal to the computer.", isCorrect: true, rationale: "The keyboard's job is to act as an input device, sending the information about which key you pressed to the computer." },
            { text: "To save the report.", isCorrect: false, rationale: "That's the hard drive's job (storage)." },
            { text: "To decide what the letter looks like.", isCorrect: false, rationale: "The font and program decide that. The keyboard just sends the signal." },
          ],
          hint: "Is the keyboard sending information in or showing information out?",
        },
        {
            id: "q11",
            question: "Why would a doctor use a computer in a hospital?",
            options: [
              { text: "To play video games during a break.", isCorrect: false, rationale: "While possible, the primary professional use is for medical tasks." },
              { text: "To keep track of patient records and view X-rays.", isCorrect: true, rationale: "Computers are essential in hospitals for managing patient data, viewing medical images, and researching treatments." },
              { text: "To order pizza for the staff.", isCorrect: false, rationale: "This is a general use, not a specific medical one." },
              { text: "To weigh patients.", isCorrect: false, rationale: "A scale weighs patients; a computer might record the weight, but it doesn't do the weighing." },
            ],
            hint: "How can a computer help a doctor be more organized and see important medical information?",
          },
          {
            id: "q12",
            question: "When you watch a video on a computer, what is the main job of the monitor?",
            options: [
              { text: "To store the video file.", isCorrect: false, rationale: "The video file is stored on the hard drive or streamed from the internet." },
              { text: "To process the video data.", isCorrect: false, rationale: "The CPU and GPU (Graphics Processing Unit) process the video data." },
              { text: "To act as an output device and display the moving pictures.", isCorrect: true, rationale: "The monitor's function is to take the processed video signal and display it for you to see (output)." },
              { text: "To download the video from the internet.", isCorrect: false, rationale: "The network card and software handle downloading." },
            ],
            hint: "The monitor's job is to let you *see* what the computer is doing.",
          },
          {
            id: "q13",
            question: "The Arithmetic Logic Unit (ALU) does more than just math. It can also make comparisons. Which of these is a comparison the ALU might make?",
            options: [
              { text: "Is the number 5 GREATER THAN the number 3?", isCorrect: true, rationale: "The ALU handles logical comparisons like greater than, less than, and equal to, which are crucial for decision-making in programs." },
              { text: "Is the color of this pixel blue?", isCorrect: false, rationale: "While the ALU is involved in the process, the GPU is specialized for handling graphics and color data." },
              { text: "Is this sentence spelled correctly?", isCorrect: false, rationale: "Spell-checking is a complex software function that uses the ALU for basic operations but isn't a direct comparison the ALU itself makes." },
              { text: "Is the volume too loud?", isCorrect: false, rationale: "Volume is managed by the operating system and audio hardware, not a direct ALU comparison." },
            ],
            hint: "The 'Logic' part of ALU means it can compare things to see if they are true or false.",
          },
          {
            id: "q14",
            question: "You are at a grocery store, and the cashier scans your items. The scanner is a type of what?",
            options: [
              { text: "Output device", isCorrect: false, rationale: "The scanner is not putting information out; it's sending it into the cash register's computer." },
              { text: "Storage device", isCorrect: false, rationale: "The scanner doesn't store the price; it just reads the barcode." },
              { text: "Input device", isCorrect: true, rationale: "The scanner reads the barcode (the input) and sends that information to the computer to find the item's price." },
              { text: "Processing device", isCorrect: false, rationale: "The computer's CPU processes the information from the scanner." },
            ],
            hint: "Is the device gathering information for the computer?",
          },
          {
            id: "q15",
            question: "What is the main difference between RAM and a Hard Drive?",
            options: [
              { text: "RAM is hardware, but a Hard Drive is software.", isCorrect: false, rationale: "Both RAM and Hard Drives are physical pieces of hardware." },
              { text: "RAM is for temporary storage while the computer is on, and the Hard Drive is for long-term storage.", isCorrect: true, rationale: "RAM is like a temporary workbench that is cleared when the power is off, while the Hard Drive is like a filing cabinet that keeps things safe." },
              { text: "RAM is an input device, and a Hard Drive is an output device.", isCorrect: false, rationale: "Both are used for storing data, not directly for input or output." },
              { text: "RAM stores pictures, and the Hard Drive stores music.", isCorrect: false, rationale: "Both can store any type of data, but they do it in different ways (temporarily vs. permanently)." },
            ],
            hint: "Think about what happens to your work when you turn the computer off.",
          },
          {
            id: "q16",
            question: "If the CPU is the computer's 'brain', what is the best description of the motherboard?",
            options: [
              { text: "The computer's eyes and ears.", isCorrect: false, rationale: "The 'eyes and ears' would be input devices like cameras and microphones." },
              { text: "The computer's skeleton and nervous system.", isCorrect: true, rationale: "The motherboard is the main circuit board that holds everything together (like a skeleton) and allows all the parts, including the CPU, to communicate (like a nervous system)." },
              { text: "The computer's voice.", isCorrect: false, rationale: "The 'voice' would be an output device like speakers." },
              { text: "The computer's long-term memory.", isCorrect: false, rationale: "That's the job of the hard drive or SSD." },
            ],
            hint: "What is the main board that everything plugs into?",
          },
          {
            id: "q17",
            question: "An architect uses a special program to design a house. This is an example of using a computer for...",
            options: [
              { text: "Communication", isCorrect: false, rationale: "While they might email the design, the act of designing itself is not communication." },
              { text: "Creativity and Design", isCorrect: true, rationale: "Computers are powerful tools for creating detailed plans and 3D models, which is a key part of design and architecture." },
              { text: "Entertainment", isCorrect: false, rationale: "While the architect might enjoy their work, the primary purpose is professional design, not entertainment like a game." },
              { text: "Calculation", isCorrect: false, rationale: "The program does many calculations, but the overall purpose of the task is design." },
            ],
            hint: "Is the architect playing, talking, or creating something new?",
          },
          {
            id: "q18",
            question: "When you print your homework, the printer is acting as an:",
            options: [
              { text: "Input device", isCorrect: false, rationale: "You are not sending information *to* the computer with the printer." },
              { text: "Output device", isCorrect: true, rationale: "The printer takes the digital information from your computer and turns it into a physical copy (output) that you can hold." },
              { text: "Storage device", isCorrect: false, rationale: "The printer doesn't store your homework file." },
              { text: "Processing device", isCorrect: false, rationale: "The computer's CPU processes the homework file before sending it to the printer." },
            ],
            hint: "Is the device giving you something *from* the computer?",
          },
          {
            id: "q19",
            question: "Which of these tasks would the computer's CPU be most responsible for?",
            options: [
              { text: "Making the screen bright.", isCorrect: false, rationale: "Screen brightness is a function of the monitor's hardware." },
              { text: "Instantly calculating the result of 1,234 x 5,678.", isCorrect: true, rationale: "The CPU, specifically its ALU, is designed to perform mathematical calculations at incredibly high speeds." },
              { text: "Storing your favorite song.", isCorrect: false, rationale: "This is the job of the hard drive or SSD (storage)." },
              { text: "Playing a beeping sound.", isCorrect: false, rationale: "This is handled by the computer's sound hardware and speakers (output)." },
            ],
            hint: "The CPU is the main 'thinking' part of the computer.",
          },
          {
            id: "q20",
            question: "You click on a video, and the Control Unit (CU) gives an order. What is the most likely sequence of events it directs?",
            options: [
              { text: "It tells the speakers to make sound, then tells the hard drive to find the file.", isCorrect: false, rationale: "It needs to find the file before it can tell the speakers to play anything." },
              { text: "It tells the hard drive to find the video file, then tells the CPU/GPU to process it, then tells the monitor/speakers to show/play it.", isCorrect: true, rationale: "This is the correct logical order: find the data, process the data, and then send it to the output devices." },
              { text: "It tells the monitor to display the video, then asks the CPU what the video is.", isCorrect: false, rationale: "The monitor can't display anything until the data has been found and processed." },
              { text: "It tells the RAM to forget everything it's doing.", isCorrect: false, rationale: "The CU needs to use RAM to process the video, not erase it." },
            ],
            hint: "Think of the logical steps: 1. Get the ingredients. 2. Prepare the meal. 3. Serve the food.",
          },
          {
            id: "q21",
            question: "What is a computer?",
            options: [
              { text: "A machine for watching movies.", isCorrect: false, rationale: "While you can watch movies on a computer, it's not its only function." },
              { text: "An electronic device for storing and processing data.", isCorrect: true, rationale: "This is the primary definition of a computer." },
              { text: "A tool for writing documents.", isCorrect: false, rationale: "A computer can be used for writing, but it's more than just a writing tool." },
              { text: "A device for playing games.", isCorrect: false, rationale: "Gaming is one of many things a computer can do." },
            ],
            hint: "Think about the main purpose of a computer.",
          },
          {
            id: "q22",
            question: "What does ICT stand for?",
            options: [
              { text: "Information and Computer Technology", isCorrect: false, rationale: "Close, but not quite right." },
              { text: "Information and Communication Technology", isCorrect: true, rationale: "ICT refers to technologies that provide access to information through telecommunications." },
              { text: "Internal Communication Technology", isCorrect: false, rationale: "This is too specific and not the correct term." },
              { text: "Information and Central Technology", isCorrect: false, rationale: "This is not the correct term." },
            ],
            hint: "What are the two main things technology helps us with?",
          },
          {
            id: "q23",
            question: "Which of the following is an example of an input device?",
            options: [
              { text: "Printer", isCorrect: false, rationale: "A printer is an output device." },
              { text: "Monitor", isCorrect: false, rationale: "A monitor is an output device." },
              { text: "Keyboard", isCorrect: true, rationale: "A keyboard is used to input text and commands." },
              { text: "Speakers", isCorrect: false, rationale: "Speakers are output devices." },
            ],
            hint: "Which device sends information to the computer?",
          },
          {
            id: "q24",
            question: "What is the function of a CPU?",
            options: [
              { text: "To display images.", isCorrect: false, rationale: "This is the function of a monitor or display screen." },
              { text: "To store files.", isCorrect: false, rationale: "This is the function of a hard drive or SSD." },
              { text: "To process data and execute commands.", isCorrect: true, rationale: "The CPU is the 'brain' of the computer." },
              { text: "To play audio.", isCorrect: false, rationale: "This is the function of speakers or headphones." },
            ],
            hint: "What does the 'brain' of the computer do?",
          },
          {
            id: "q25",
            question: "Which of the following is a type of computer memory?",
            options: [
              { text: "CPU", isCorrect: false, rationale: "The CPU is the processor, not memory." },
              { text: "RAM", isCorrect: true, rationale: "RAM (Random Access Memory) is a type of volatile memory." },
              { text: "GPU", isCorrect: false, rationale: "The GPU is the graphics processing unit." },
              { text: "PSU", isCorrect: false, rationale: "The PSU is the power supply unit." },
            ],
            hint: "Which of these is a temporary storage for data?",
          },
          {
            id: "q26",
            question: "How are computers used in education?",
            options: [
              { text: "For online learning and research.", isCorrect: true, rationale: "Computers provide access to a vast amount of information and online courses." },
              { text: "Only for playing games.", isCorrect: false, rationale: "While games can be educational, it's not the only use of computers in education." },
              { text: "To replace teachers.", isCorrect: false, rationale: "Computers are a tool to aid learning, not replace teachers." },
              { text: "To watch movies.", isCorrect: false, rationale: "This is a recreational use, not an educational one." },
            ],
            hint: "How do students use computers for their studies?",
          },
          {
            id: "q27",
            question: "What is the purpose of a storage device?",
            options: [
              { text: "To process information.", isCorrect: false, rationale: "This is the function of the CPU." },
              { text: "To display information.", isCorrect: false, rationale: "This is the function of a monitor." },
              { text: "To store data for long-term use.", isCorrect: true, rationale: "Storage devices like hard drives and SSDs are used for permanent storage." },
              { text: "To input data.", isCorrect: false, rationale: "This is the function of input devices like keyboards and mice." },
            ],
            hint: "Where do you save your files so you can use them later?",
          },
          {
            id: "q28",
            question: "Which of these is NOT a basic component of a computer system?",
            options: [
              { text: "CPU", isCorrect: false, rationale: "The CPU is a core component." },
              { text: "Memory", isCorrect: false, rationale: "Memory is essential for a computer to function." },
              { text: "Internet Connection", isCorrect: true, rationale: "A computer can function without an internet connection." },
              { text: "Storage", isCorrect: false, rationale: "Storage is a fundamental component." },
            ],
            hint: "Which of these is not required for a computer to work on its own?",
          },
          {
            id: "q29",
            question: "What is computer hardware?",
            options: [
              { text: "The programs and applications on a computer.", isCorrect: false, rationale: "This is software." },
              { text: "The physical parts of a computer.", isCorrect: true, rationale: "Hardware includes all the physical components you can touch." },
              { text: "The data stored on a computer.", isCorrect: false, rationale: "This is data, not hardware." },
              { text: "The internet connection.", isCorrect: false, rationale: "This is a service, not a physical part of the computer itself." },
            ],
            hint: "What can you physically touch on a computer?",
          },
          {
            id: "q30",
            question: "How do banks use computers?",
            options: [
              { text: "To manage customer accounts and transactions.", isCorrect: true, rationale: "Computers are essential for modern banking operations." },
              { text: "To bake bread.", isCorrect: false, rationale: "This is not a function of computers in a bank." },
              { text: "To fly airplanes.", isCorrect: false, rationale: "This is a use of computers in aviation, not banking." },
              { text: "To write novels.", isCorrect: false, rationale: "This is a use of computers in writing, not banking." },
            ],
            hint: "How does a bank keep track of your money?",
          }
        ],
      },
    hi: {
      home: "होम",
      question: "प्रश्न",
      score: "स्कोर",
      bestOfLuck: "क्विज़ के लिए शुभकामनाएँ!",
      startQuiz: "क्विज़ शुरू करें",
      nextQuestion: "अगला प्रश्न",
      submit: "सबमिट करें",
      playAgain: "फिर से खेलें",
      quizComplete: "क्विज़ पूरा हुआ!",
      showHint: "संकेत दिखाएँ",
      hideHint: "संकेत छिपाएँ",
      welcomeMessage: "कंप्यूटर क्विज़ में आपका स्वागत है! शुरू करने के लिए अपना नाम दर्ज करें।",
      nameLabel: "आपका नाम",
      nameRequired: "क्विज़ शुरू करने के लिए कृपया अपना नाम दर्ज करें।",
      timesUp: "समय समाप्त!",
      results: {
        failed: "असफल",
        passed: "उत्तीर्ण",
        c_grade: "ग्रेड: C",
        b_grade: "ग्रेड: B",
        a_grade: "ग्रेड: A",
        excellent: "बहुत बढ़िया!",
        failedMessage: "चिंता न करें, {studentName}। हर विशेषज्ञ कभी नौसिखिया ही था। प्रयास करते रहें!",
        passedMessage: "बहुत अच्छा, {studentName}! आपने क्विज़ पास कर लिया है।",
        c_gradeMessage: "बहुत अच्छा, {studentName}! आप इसे समझने लगे हैं।",
        b_gradeMessage: "बहुत बढ़िया, {studentName}! आपकी समझ काफ़ी अच्छी है।",
        a_gradeMessage: "उत्कृष्ट, {studentName}! आप तो सितारे हैं!",
        excellentMessage: "असाधारण, {studentName}! आप तो कंप्यूटर के विशेषज्ञ हैं!",
      },
      quizData: [
        {
          id: "q1",
          question: "यदि आप कंप्यूटर पर चित्र बना रहे हैं, तो आप अपनी ड्राइंग को अपने हाथ से कंप्यूटर में लाने के लिए किस उपकरण का उपयोग कर रहे हैं?",
          options: [
            { text: "मॉनिटर", isCorrect: false, rationale: "एक मॉनिटर आपको तस्वीर दिखाता है (आउटपुट), लेकिन आपको इसे कंप्यूटर में बनाने नहीं देता।" },
            { text: "प्रिंटर", isCorrect: false, rationale: "एक प्रिंटर कंप्यूटर से तस्वीर लेता है और उसे कागज पर डालता है (आउटपुट)।" },
            { text: "माउस या ड्रॉइंग टैबलेट", isCorrect: true, rationale: "माउस या एक विशेष ड्राइंग टैबलेट का उपयोग आपके हाथ की गतिविधियों को कंप्यूटर में भेजने के लिए किया जाता है (इनपुट)।" },
            { text: "स्पीकर", isCorrect: false, rationale: "स्पीकर ध्वनि के लिए हैं (आउटपुट), ड्राइंग के लिए नहीं।" },
          ],
          hint: "सोचें कि कौन सा उपकरण आपको जानकारी 'डालने' देता है।",
        },
        {
          id: "q2",
          question: "एक बेकर यह जानने के लिए एक रेसिपी का उपयोग करता है कि कितना आटा और चीनी मिलानी है। कंप्यूटर में, कौन सा हिस्सा रेसिपी की तरह काम करता है, जो अन्य सभी हिस्सों को बताता है कि क्या करना है?",
          options: [
            { text: "मॉनिटर", isCorrect: false, rationale: "मॉनिटर सिर्फ परिणाम दिखाता है, जैसे सजा हुआ केक। यह निर्देश नहीं देता है।" },
            { text: "कंट्रोल यूनिट (CU)", isCorrect: true, rationale: "कंट्रोल यूनिट (CU) डेटा और निर्देशों के प्रवाह को निर्देशित करता है, ठीक वैसे ही जैसे एक रेसिपी बेकर का मार्गदर्शन करती है।" },
            { text: "हार्ड ड्राइव", isCorrect: false, rationale: "हार्ड ड्राइव पेंट्री की तरह है जहाँ आप बाद के लिए सामग्री (डेटा) संग्रहीत करते हैं, रेसिपी नहीं।" },
            { text: "बिजली की आपूर्ति", isCorrect: false, rationale: "बिजली की आपूर्ति ऊर्जा प्रदान करती है, जैसे ओवन की गर्मी, लेकिन निर्देश नहीं देती है।" },
          ],
          hint: "सीपीयू का कौन सा हिस्सा 'निर्देशक' या 'प्रबंधक' है?",
        },
        {
          id: "q3",
          question: "आपको अपना गणित का होमवर्क करना है, जिसमें कई जोड़ने और घटाने वाले सवाल हैं। सीपीयू का कौन सा हिस्सा कैलकुलेटर की तरह है जो आपके लिए सारी गणनाएँ करेगा?",
          options: [
            { text: "रैम", isCorrect: false, rationale: "रैम आपके कार्यक्षेत्र की तरह है, जो होमवर्क (डेटा) को अस्थायी रूप से रखता है, लेकिन यह गणना नहीं करता है।" },
            { text: "कंट्रोल यूनिट (CU)", isCorrect: false, rationale: "कंट्रोल यूनिट कंप्यूटर को बताता है कि *क्या* करना है, लेकिन यह खुद गणित नहीं करता है।" },
            { text: "अरिथमैटिक लॉजिक यूनिट (ALU)", isCorrect: true, rationale: "ALU सीपीयू का वह हिस्सा है जो सभी अंकगणितीय (जैसे जोड़) और तार्किक संचालन करता है।" },
            { text: "कीबोर्ड", isCorrect: false, rationale: "कीबोर्ड का उपयोग संख्याओं को टाइप करने के लिए किया जाता है (इनपुट), उनकी गणना करने के लिए नहीं।" },
          ],
          hint: "सीपीयू के किस हिस्से के नाम में 'अरिथमैटिक' है?",
        },
        {
          id: "q4",
          question: "आपका दोस्त आपके कंप्यूटर पर मौजूद एक गाना सुनना चाहता है। कंप्यूटर आपके दोस्त तक आवाज़ कैसे पहुँचाता है?",
          options: [
            { text: "कीबोर्ड के माध्यम से", isCorrect: false, rationale: "एक कीबोर्ड जानकारी डालने के लिए है, ध्वनि निकालने के लिए नहीं।" },
            { text: "स्पीकर के माध्यम से", isCorrect: true, rationale: "स्पीकर आउटपुट डिवाइस हैं जो विशेष रूप से विद्युत संकेतों को ध्वनि में बदलने के लिए डिज़ाइन किए गए हैं।" },
            { text: "माउस के माध्यम से", isCorrect: false, rationale: "एक माउस कर्सर को नियंत्रित करने और क्लिक करने के लिए है (इनपुट)।" },
            { text: "सीपीयू के माध्यम से", isCorrect: false, rationale: "सीपीयू गीत फ़ाइल को संसाधित करता है, लेकिन यह वह ध्वनि उत्पन्न नहीं करता है जिसे आप सुनते हैं।" },
          ],
          hint: "कौन सा उपकरण शोर करता है?",
        },
        {
          id: "q5",
          question: "सोचिए कि सीपीयू की कंट्रोल यूनिट एक ट्रैफिक पुलिस की तरह है। कंप्यूटर में उसका मुख्य काम क्या है?",
          options: [
            { text: "सभी गणित की समस्याओं को हल करना।", isCorrect: false, rationale: "यह ALU (अरिथमैटिक लॉजिक यूनिट) का काम है, जो एक सुपर-फास्ट कैलकुलेटर की तरह है।" },
            { text: "आपके सभी गेम और फ़ोटो संग्रहीत करना।", isCorrect: false, rationale: "यह हार्ड ड्राइव या एसएसडी का काम है, जो दीर्घकालिक भंडारण है।" },
            { text: "कंप्यूटर के सभी हिस्सों के बीच सूचना के प्रवाह को निर्देशित करना।", isCorrect: true, rationale: "एक ट्रैफिक पुलिस की तरह, CU यह निर्देशित करता है कि डेटा कहाँ जाना चाहिए, यह सुनिश्चित करते हुए कि सब कुछ सही क्रम में हो।" },
            { text: "स्क्रीन पर चित्र दिखाना।", isCorrect: false, rationale: "यह ग्राफिक्स कार्ड और मॉनिटर का काम है।" },
          ],
          hint: "एक ट्रैफिक पुलिस गति और दिशा का प्रबंधन करती है।",
        },
        {
          id: "q6",
          question: "आप एक वीडियो गेम खेलते हुए 'जंप' बटन दबाते हैं। यह क्रिया किसका उदाहरण है?",
          options: [
            { text: "इनपुट", isCorrect: true, rationale: "आप कंप्यूटर *में* एक कमांड भेज रहे हैं, अपने चरित्र को कूदने के लिए कह रहे हैं।" },
            { text: "आउटपुट", isCorrect: false, rationale: "स्क्रीन पर कूदने वाला चरित्र आउटपुट है। बटन दबाना इनपुट है।" },
            { text: "भंडारण", isCorrect: false, rationale: "भंडारण खेल को सहेजने के लिए है ताकि आप इसे बाद में खेल सकें।" },
            { text: "प्रसंस्करण", isCorrect: false, rationale: "सीपीयू द्वारा जंप कमांड का प्रसंस्करण प्रसंस्करण चरण है, जो आपके इनपुट के बाद होता है।" },
          ],
          hint: "क्या आप कंप्यूटर को कुछ बता रहे हैं, या यह आपको कुछ बता रहा है?",
        },
        {
          id: "q7",
          question: "इनमें से कौन सा एक कंप्यूटर हार्डवेयर नहीं है?",
          options: [
            { text: "सीपीयू चिप", isCorrect: false, rationale: "सीपीयू एक भौतिक चिप है, इसलिए यह हार्डवेयर है।" },
            { text: "रैम स्टिक्स", isCorrect: false, rationale: "रैम स्टिक्स भौतिक सर्किट बोर्ड हैं, इसलिए वे हार्डवेयर हैं।" },
            { text: "आप जो वीडियो गेम खेल रहे हैं", isCorrect: true, rationale: "एक वीडियो गेम एक प्रोग्राम है, जो सॉफ्टवेयर है। आप गेम को शारीरिक रूप से नहीं छू सकते।" },
            { text: "कंप्यूटर माउस", isCorrect: false, rationale: "माउस एक भौतिक उपकरण है जिसे आप पकड़ सकते हैं, इसलिए यह हार्डवेयर है।" },
          ],
          hint: "हार्डवेयर एक कंप्यूटर के भौतिक हिस्से हैं जिन्हें आप छू सकते हैं।",
        },
        {
          id: "q8",
          question: "अगर आप अपनी बनाई हुई ड्राइंग सहेजना चाहते हैं ताकि आप उसे कल अपने परिवार को दिखा सकें, तो कंप्यूटर उसे कहाँ रखेगा?",
          options: [
            { text: "रैम में", isCorrect: false, rationale: "रैम अस्थायी मेमोरी है, जैसे एक व्हाइटबोर्ड। जब आप कंप्यूटर बंद करते हैं तो यह मिटा दिया जाता है।" },
            { text: "हार्ड ड्राइव पर", isCorrect: true, rationale: "हार्ड ड्राइव दीर्घकालिक भंडारण के लिए है। वहां सहेजी गई फाइलें कंप्यूटर बंद होने के बाद भी रहेंगी।" },
            { text: "मॉनिटर पर", isCorrect: false, rationale: "मॉनिटर केवल ड्राइंग प्रदर्शित करता है; यह इसे सहेजता नहीं है।" },
            { text: "सीपीयू में", isCorrect: false, rationale: "सीपीयू ड्राइंग को संसाधित करता है, लेकिन यह इसे लंबी अवधि के लिए संग्रहीत नहीं करता है।" },
          ],
          hint: "कौन सा हिस्सा स्थायी, दीर्घकालिक बचत के लिए उपयोग किया जाता है?",
        },
        {
          id: "q9",
          question: "सीपीयू कंप्यूटर का 'दिमाग' होता है। यह दो मुख्य हिस्सों से बना है जो मिलकर काम करते हैं। वे कौन से हैं?",
          options: [
            { text: "कीबोर्ड और माउस", isCorrect: false, rationale: "कीबोर्ड और माउस इनपुट डिवाइस हैं, जो सीपीयू से अलग हैं।" },
            { text: "रैम और हार्ड ड्राइव", isCorrect: false, rationale: "रैम और हार्ड ड्राइव मेमोरी/स्टोरेज के प्रकार हैं, न कि सीपीयू के मुख्य प्रसंस्करण भाग।" },
            { text: "कंट्रोल यूनिट (CU) और अरिथमैटिक लॉजिक यूनिट (ALU)", isCorrect: true, rationale: "CU कार्यों को निर्देशित करता है और ALU गणना करता है। साथ में, वे सीपीयू का मूल बनाते हैं।" },
            { text: "मॉनिटर और स्पीकर", isCorrect: false, rationale: "मॉनिटर और स्पीकर आउटपुट डिवाइस हैं।" },
          ],
          hint: "एक हिस्सा 'निर्देशक' है और दूसरा 'कैलकुलेटर' है।",
        },
        {
          id: "q10",
          question: "आप स्कूल की रिपोर्ट लिख रहे हैं और कीबोर्ड पर एक अक्षर दबाते हैं। इस प्रक्रिया में कीबोर्ड का क्या काम है?",
          options: [
            { text: "स्क्रीन पर अक्षर दिखाना।", isCorrect: false, rationale: "यह मॉनिटर का काम है (आउटपुट)।" },
            { text: "अक्षर का संकेत कंप्यूटर को भेजना।", isCorrect: true, rationale: "कीबोर्ड का काम एक इनपुट डिवाइस के रूप में कार्य करना है, जो आपके द्वारा दबाए गए कुंजी के बारे में जानकारी कंप्यूटर को भेजता है।" },
            { text: "रिपोर्ट को सहेजना।", isCorrect: false, rationale: "यह हार्ड ड्राइव का काम है (भंडारण)।" },
            { text: "यह तय करना कि अक्षर कैसा दिखता है।", isCorrect: false, rationale: "फ़ॉन्ट और प्रोग्राम यह तय करते हैं। कीबोर्ड सिर्फ संकेत भेजता है।" },
          ],
          hint: "क्या कीबोर्ड जानकारी अंदर भेज रहा है या जानकारी बाहर दिखा रहा है?",
        },
        {
            id: "q11",
            question: "एक डॉक्टर अस्पताल में कंप्यूटर का इस्तेमाल क्यों करेगा?",
            options: [
              { text: "ब्रेक के दौरान वीडियो गेम खेलने के लिए।", isCorrect: false, rationale: "हालांकि संभव है, प्राथमिक पेशेवर उपयोग चिकित्सा कार्यों के लिए है।" },
              { text: "रोगी के रिकॉर्ड पर नज़र रखने और एक्स-रे देखने के लिए।", isCorrect: true, rationale: "रोगी डेटा के प्रबंधन, चिकित्सा छवियों को देखने और उपचार पर शोध के लिए अस्पतालों में कंप्यूटर आवश्यक हैं।" },
              { text: "कर्मचारियों के लिए पिज्जा ऑर्डर करने के लिए।", isCorrect: false, rationale: "यह एक सामान्य उपयोग है, एक विशिष्ट चिकित्सा उपयोग नहीं।" },
              { text: "रोगियों का वजन करने के लिए।", isCorrect: false, rationale: "एक पैमाना रोगियों का वजन करता है; एक कंप्यूटर वजन रिकॉर्ड कर सकता है, लेकिन यह वजन नहीं करता है।" },
            ],
            hint: "एक कंप्यूटर डॉक्टर को अधिक संगठित होने और महत्वपूर्ण चिकित्सा जानकारी देखने में कैसे मदद कर सकता है?",
          },
          {
            id: "q12",
            question: "जब आप कंप्यूटर पर एक वीडियो देखते हैं, तो मॉनिटर का मुख्य काम क्या होता है?",
            options: [
              { text: "वीडियो फ़ाइल को संग्रहीत करने के लिए।", isCorrect: false, rationale: "वीडियो फ़ाइल हार्ड ड्राइव पर संग्रहीत होती है या इंटरनेट से स्ट्रीम की जाती है।" },
              { text: "वीडियो डेटा को संसाधित करने के लिए।", isCorrect: false, rationale: "सीपीयू और जीपीयू (ग्राफिक्स प्रोसेसिंग यूनिट) वीडियो डेटा को संसाधित करते हैं।" },
              { text: "एक आउटपुट डिवाइस के रूप में कार्य करना और चलती तस्वीरों को प्रदर्शित करना।", isCorrect: true, rationale: "मॉनिटर का कार्य संसाधित वीडियो सिग्नल लेना और इसे आपको देखने के लिए प्रदर्शित करना है (आउटपुट)।" },
              { text: "इंटरनेट से वीडियो डाउनलोड करने के लिए।", isCorrect: false, rationale: "नेटवर्क कार्ड और सॉफ्टवेयर डाउनलोडिंग को संभालते हैं।" },
            ],
            hint: "मॉनिटर का काम आपको यह देखने देना है कि कंप्यूटर क्या कर रहा है।",
          },
          {
            id: "q13",
            question: "अरिथमैटिक लॉजिक यूनिट (ALU) सिर्फ़ गणित ही नहीं करता, यह तुलना भी कर सकता है। इनमें से कौन सी तुलना ALU कर सकता है?",
            options: [
              { text: "क्या संख्या 5, संख्या 3 से बड़ी है?", isCorrect: true, rationale: "ALU तार्किक तुलनाओं को संभालता है जैसे कि से बड़ा, से कम, और बराबर, जो कार्यक्रमों में निर्णय लेने के लिए महत्वपूर्ण हैं।" },
              { text: "क्या इस पिक्सेल का रंग नीला है?", isCorrect: false, rationale: "जबकि ALU इस प्रक्रिया में शामिल है, GPU ग्राफिक्स और रंग डेटा को संभालने के लिए विशिष्ट है।" },
              { text: "क्या यह वाक्य सही ढंग से लिखा गया है?", isCorrect: false, rationale: "वर्तनी-जांच एक जटिल सॉफ्टवेयर फ़ंक्शन है जो बुनियादी संचालन के लिए ALU का उपयोग करता है लेकिन यह ALU द्वारा की जाने वाली सीधी तुलना नहीं है।" },
              { text: "क्या वॉल्यूम बहुत तेज़ है?", isCorrect: false, rationale: "वॉल्यूम का प्रबंधन ऑपरेटिंग सिस्टम और ऑडियो हार्डवेयर द्वारा किया जाता है, न कि प्रत्यक्ष ALU तुलना द्वारा।" },
            ],
            hint: "ALU का 'लॉजिक' हिस्सा मतलब है कि यह चीजों की तुलना कर सकता है यह देखने के लिए कि क्या वे सही हैं या गलत।",
          },
          {
            id: "q14",
            question: "आप एक किराने की दुकान पर हैं और कैशियर आपके सामान को स्कैन करता है। स्कैनर किस तरह का उपकरण है?",
            options: [
              { text: "आउटपुट डिवाइस", isCorrect: false, rationale: "स्कैनर जानकारी बाहर नहीं डाल रहा है; यह इसे कैश रजिस्टर के कंप्यूटर में भेज रहा है।" },
              { text: "भंडारण डिवाइस", isCorrect: false, rationale: "स्क্যানर मूल्य संग्रहीत नहीं करता है; यह सिर्फ बारकोड पढ़ता है।" },
              { text: "इनपुट डिवाइस", isCorrect: true, rationale: "स्कैनर बारकोड (इनपुट) पढ़ता है और उस जानकारी को कंप्यूटर को भेजता है ताकि आइटम की कीमत का पता चल सके।" },
              { text: "प्रसंस्करण डिवाइस", isCorrect: false, rationale: "कंप्यूटर का सीपीयू स्कैनर से जानकारी संसाधित करता है।" },
            ],
            hint: "क्या डिवाइस कंप्यूटर के लिए जानकारी एकत्र कर रहा है?",
          },
          {
            id: "q15",
            question: "रैम और हार्ड ड्राइव के बीच मुख्य अंतर क्या है?",
            options: [
              { text: "रैम हार्डवेयर है, लेकिन हार्ड ड्राइव सॉफ्टवेयर है।", isCorrect: false, rationale: "रैम और हार्ड ड्राइव दोनों ही भौतिक हार्डवेयर के टुकड़े हैं।" },
              { text: "रैम अस्थायी भंडारण के लिए है जब कंप्यूटर चालू होता है, और हार्ड ड्राइव दीर्घकालिक भंडारण के लिए है।", isCorrect: true, rationale: "रैम एक अस्थायी कार्यक्षेत्र की तरह है जो बिजली बंद होने पर साफ हो जाता है, जबकि हार्ड ड्राइव एक फाइलिंग कैबिनेट की तरह है जो चीजों को सुरक्षित रखता है।" },
              { text: "रैम एक इनपुट डिवाइस है, और हार्ड ड्राइव एक आउटपुट डिवाइस है।", isCorrect: false, rationale: "दोनों का उपयोग डेटा संग्रहीत करने के लिए किया जाता है, सीधे इनपुट या आउटपुट के लिए नहीं।" },
              { text: "रैम तस्वीरें संग्रहीत करता है, और हार्ड ड्राइव संगीत संग्रहीत करता है।", isCorrect: false, rationale: "दोनों किसी भी प्रकार का डेटा संग्रहीत कर सकते हैं, लेकिन वे इसे अलग-अलग तरीकों से करते हैं (अस्थायी बनाम स्थायी)।" },
            ],
            hint: "सोचें कि जब आप कंप्यूटर बंद करते हैं तो आपके काम का क्या होता है।",
          },
          {
            id: "q16",
            question: "अगर सीपीयू कंप्यूटर का 'दिमाग' है, तो मदरबोर्ड का सबसे अच्छा वर्णन क्या होगा?",
            options: [
              { text: "कंप्यूटर की आंखें और कान।", isCorrect: false, rationale: "'आंखें और कान' कैमरे और माइक्रोफोन जैसे इनपुट डिवाइस होंगे।" },
              { text: "कंप्यूटर का कंकाल और तंत्रिका तंत्र।", isCorrect: true, rationale: "मदरबोर्ड मुख्य सर्किट बोर्ड है जो सब कुछ एक साथ रखता है (एक कंकाल की तरह) और सीपीयू सहित सभी भागों को संवाद करने की अनुमति देता है (एक तंत्रिका तंत्र की तरह)।" },
              { text: "कंप्यूटर की आवाज।", isCorrect: false, rationale: "'आवाज' स्पीकर जैसे आउटपुट डिवाइस होगी।" },
              { text: "कंप्यूटर की दीर्घकालिक मेमोरी।", isCorrect: false, rationale: "यह हार्ड ड्राइव या एसएसडी का काम है।" },
            ],
            hint: "मुख्य बोर्ड क्या है जिसमें सब कुछ प्लग होता है?",
          },
          {
            id: "q17",
            question: "एक आर्किटेक्ट घर डिजाइन करने के लिए एक खास प्रोग्राम का इस्तेमाल करता है। यह कंप्यूटर के इस्तेमाल का एक उदाहरण है...",
            options: [
              { text: "संचार", isCorrect: false, rationale: "जबकि वे डिजाइन को ईमेल कर सकते हैं, डिजाइनिंग का कार्य स्वयं संचार नहीं है।" },
              { text: "रचनात्मकता और डिजाइन", isCorrect: true, rationale: "कंप्यूटर विस्तृत योजनाओं और 3 डी मॉडल बनाने के लिए शक्तिशाली उपकरण हैं, जो डिजाइन और वास्तुकला का एक महत्वपूर्ण हिस्सा है।" },
              { text: "मनोरंजन", isCorrect: false, rationale: "जबकि वास्तुकार अपने काम का आनंद ले सकता है, प्राथमिक उद्देश्य पेशेवर डिजाइन है, न कि एक खेल की तरह मनोरंजन।" },
              { text: "गणना", isCorrect: false, rationale: "कार्यक्रम कई गणना करता है, लेकिन कार्य का समग्र उद्देश्य डिजाइन है।" },
            ],
            hint: "क्या वास्तुकार खेल रहा है, बात कर रहा है, या कुछ नया बना रहा है?",
          },
          {
            id: "q18",
            question: "जब आप अपना होमवर्क प्रिंट करते हैं, तो प्रिंटर किस तरह काम कर रहा होता है?",
            options: [
              { text: "इनपुट डिवाइस", isCorrect: false, rationale: "आप प्रिंटर के साथ कंप्यूटर *को* जानकारी नहीं भेज रहे हैं।" },
              { text: "आउटपुट डिवाइस", isCorrect: true, rationale: "प्रिंटर आपके कंप्यूटर से डिजिटल जानकारी लेता है और इसे एक भौतिक प्रति (आउटपुट) में बदल देता है जिसे आप पकड़ सकते हैं।" },
              { text: "भंडारण डिवाइस", isCorrect: false, rationale: "प्रिंटर आपकी होमवर्क फ़ाइल संग्रहीत नहीं करता है।" },
              { text: "प्रसंस्करण डिवाइस", isCorrect: false, rationale: "कंप्यूटर का सीपीयू प्रिंटर को भेजने से पहले होमवर्क फ़ाइल को संसाधित करता है।" },
            ],
            hint: "क्या डिवाइस आपको कंप्यूटर *से* कुछ दे रहा है?",
          },
          {
            id: "q19",
            question: "इनमें से कौन सा काम मुख्य रूप से सीपीयू का है?",
            options: [
              { text: "स्क्रीन को उज्ज्वल बनाना।", isCorrect: false, rationale: "स्क्रीन की चमक मॉनिटर के हार्डवेयर का एक कार्य है।" },
              { text: "1,234 x 5,678 के परिणाम की तुरंत गणना करना।", isCorrect: true, rationale: "सीपीयू, विशेष रूप से इसका एएलयू, अविश्वसनीय रूप से उच्च गति पर गणितीय गणना करने के लिए डिज़ाइन किया गया है।" },
              { text: "अपना पसंदीदा गीत संग्रहीत करना।", isCorrect: false, rationale: "यह हार्ड ड्राइव या एसएसडी (भंडारण) का काम है।" },
              { text: "एक बीपिंग ध्वनि बजाना।", isCorrect: false, rationale: "यह कंप्यूटर के साउंड हार्डवेयर और स्पीकर (आउटपुट) द्वारा नियंत्रित किया जाता है।" },
            ],
            hint: "सीपीयू कंप्यूटर का मुख्य 'सोच' वाला हिस्सा है।",
          },
          {
            id: "q20",
            question: "आप एक वीडियो पर क्लिक करते हैं और कंट्रोल यूनिट (CU) एक आदेश देता है। इसके बाद होने वाली घटनाओं का सबसे संभावित क्रम क्या है?",
            options: [
              { text: "यह स्पीकर को ध्वनि बनाने के लिए कहता है, फिर हार्ड ड्राइव को फ़ाइल खोजने के लिए कहता है।", isCorrect: false, rationale: "इसे कुछ भी बजाने के लिए स्पीकर को कहने से पहले फ़ाइल ढूंढनी होगी।" },
              { text: "यह हार्ड ड्राइव को वीडियो फ़ाइल खोजने के लिए कहता है, फिर सीपीयू/जीपीयू को इसे संसाधित करने के लिए कहता है, फिर मॉनिटर/स्पीकर को इसे दिखाने/चलाने के लिए कहता है।", isCorrect: true, rationale: "यह सही तार्किक क्रम है: डेटा ढूंढें, डेटा संसाधित करें, और फिर इसे आउटपुट डिवाइस पर भेजें।" },
              { text: "यह मॉनिटर को वीडियो प्रदर्शित करने के लिए कहता है, फिर सीपीयू से पूछता है कि वीडियो क्या है।", isCorrect: false, rationale: "मॉनिटर तब तक कुछ भी प्रदर्शित नहीं कर सकता जब तक डेटा मिल और संसाधित न हो जाए।" },
              { text: "यह रैम को वह सब कुछ भूलने के लिए कहता है जो वह कर रहा है।", isCorrect: false, rationale: "सीयू को वीडियो संसाधित करने के लिए रैम का उपयोग करने की आवश्यकता है, न कि इसे मिटाने की।" },
            ],
            hint: "तार्किक चरणों के बारे में सोचें: 1. सामग्री प्राप्त करें। 2. भोजन तैयार करें। 3. भोजन परोसें।",
          },
          {
            id: "q21",
            question: "कंप्यूटर क्या है?",
            options: [
              { text: "फिल्में देखने की मशीन।", isCorrect: false, rationale: "आप कंप्यूटर पर फिल्में देख सकते हैं, लेकिन यह इसका एकमात्र कार्य नहीं है।" },
              { text: "डेटा संग्रहीत करने और संसाधित करने के लिए एक इलेक्ट्रॉनिक उपकरण।", isCorrect: true, rationale: "यह कंप्यूटर की प्राथमिक परिभाषा है।" },
              { text: "दस्तावेज़ लिखने का एक उपकरण।", isCorrect: false, rationale: "कंप्यूटर का उपयोग लिखने के लिए किया जा सकता है, लेकिन यह केवल एक लेखन उपकरण से कहीं अधिक है।" },
              { text: "गेम खेलने का एक उपकरण।", isCorrect: false, rationale: "गेमिंग उन कई चीजों में से एक है जो एक कंप्यूटर कर सकता है।" },
            ],
            hint: "कंप्यूटर के मुख्य उद्देश्य के बारे में सोचें।",
          },
          {
            id: "q22",
            question: "ICT का मतलब क्या है?",
            options: [
              { text: "सूचना और कंप्यूटर प्रौद्योगिकी", isCorrect: false, rationale: "करीब है, लेकिन पूरी तरह से सही नहीं है।" },
              { text: "सूचना और संचार प्रौद्योगिकी", isCorrect: true, rationale: "ICT उन प्रौद्योगिकियों को संदर्भित करता है जो दूरसंचार के माध्यम से सूचना तक पहुंच प्रदान करती हैं।" },
              { text: "आंतरिक संचार प्रौद्योगिकी", isCorrect: false, rationale: "यह बहुत विशिष्ट है और सही शब्द नहीं है।" },
              { text: "सूचना और केंद्रीय प्रौद्योगिकी", isCorrect: false, rationale: "यह सही शब्द नहीं है।" },
            ],
            hint: "प्रौद्योगिकी हमें किन दो मुख्य चीजों में मदद करती है?",
          },
          {
            id: "q23",
            question: "निम्नलिखित में से कौन सा इनपुट डिवाइस का एक उदाहरण है?",
            options: [
              { text: "प्रिंटर", isCorrect: false, rationale: "प्रिंटर एक आउटपुट डिवाइस है।" },
              { text: "मॉनिटर", isCorrect: false, rationale: "मॉनिटर एक आउटपुट डिवाइस है।" },
              { text: "कीबोर्ड", isCorrect: true, rationale: "कीबोर्ड का उपयोग टेक्स्ट और कमांड इनपुट करने के लिए किया जाता है।" },
              { text: "स्पीकर", isCorrect: false, rationale: "स्पीकर आउटपुट डिवाइस हैं।" },
            ],
            hint: "कौन सा उपकरण कंप्यूटर को जानकारी भेजता है?",
          },
          {
            id: "q24",
            question: "सीपीयू का कार्य क्या है?",
            options: [
              { text: "छवियों को प्रदर्शित करना।", isCorrect: false, rationale: "यह एक मॉनिटर या डिस्प्ले स्क्रीन का कार्य है।" },
              { text: "फ़ाइलों को संग्रहीत करना।", isCorrect: false, rationale: "यह एक हार्ड ड्राइव या एसएसडी का कार्य है।" },
              { text: "डेटा को संसाधित करना और कमांड निष्पादित करना।", isCorrect: true, rationale: "सीपीयू कंप्यूटर का 'मस्तिष्क' है।" },
              { text: "ऑडियो चलाना।", isCorrect: false, rationale: "यह स्पीकर या हेडफ़ोन का कार्य है।" },
            ],
            hint: "कंप्यूटर का 'मस्तिष्क' क्या करता है?",
          },
          {
            id: "q25",
            question: "निम्नलिखित में से कौन सा एक प्रकार का कंप्यूटर मेमोरी है?",
            options: [
              { text: "सीपीयू", isCorrect: false, rationale: "सीपीयू प्रोसेसर है, मेमोरी नहीं।" },
              { text: "रैम", isCorrect: true, rationale: "रैम (रैंडम एक्सेस मेमोरी) एक प्रकार की अस्थिर मेमोरी है।" },
              { text: "जीपीयू", isCorrect: false, rationale: "जीपीयू ग्राफिक्स प्रोसेसिंग यूनिट है।" },
              { text: "पीएसयू", isCorrect: false, rationale: "पीएसयू बिजली आपूर्ति इकाई है।" },
            ],
            hint: "इनमें से कौन सा डेटा के लिए एक अस्थायी भंडारण है?",
          },
          {
            id: "q26",
            question: "शिक्षा में कंप्यूटर का उपयोग कैसे किया जाता है?",
            options: [
              { text: "ऑनलाइन सीखने और शोध के लिए।", isCorrect: true, rationale: "कंप्यूटर बड़ी मात्रा में जानकारी और ऑनलाइन पाठ्यक्रमों तक पहुंच प्रदान करते हैं।" },
              { text: "केवल गेम खेलने के लिए।", isCorrect: false, rationale: "हालांकि खेल शैक्षिक हो सकते हैं, लेकिन यह शिक्षा में कंप्यूटर का एकमात्र उपयोग नहीं है।" },
              { text: "शिक्षकों को बदलने के लिए।", isCorrect: false, rationale: "कंप्यूटर सीखने में सहायता करने का एक उपकरण है, शिक्षकों को बदलने का नहीं।" },
              { text: "फिल्में देखने के लिए।", isCorrect: false, rationale: "यह एक मनोरंजक उपयोग है, शैक्षिक नहीं।" },
            ],
            hint: "छात्र अपनी पढ़ाई के लिए कंप्यूटर का उपयोग कैसे करते हैं?",
          },
          {
            id: "q27",
            question: "एक भंडारण उपकरण का उद्देश्य क्या है?",
            options: [
              { text: "जानकारी संसाधित करना।", isCorrect: false, rationale: "यह सीपीयू का कार्य है।" },
              { text: "जानकारी प्रदर्शित करना।", isCorrect: false, rationale: "यह एक मॉनिटर का कार्य है।" },
              { text: "दीर्घकालिक उपयोग के लिए डेटा संग्रहीत करना।", isCorrect: true, rationale: "हार्ड ड्राइव और एसएसडी जैसे भंडारण उपकरणों का उपयोग स्थायी भंडारण के लिए किया जाता है।" },
              { text: "डेटा इनपुट करना।", isCorrect: false, rationale: "यह कीबोर्ड और माउस जैसे इनपुट उपकरणों का कार्य है।" },
            ],
            hint: "आप अपनी फ़ाइलों को कहाँ सहेजते हैं ताकि आप उन्हें बाद में उपयोग कर सकें?",
          },
          {
            id: "q28",
            question: "इनमें से कौन सा कंप्यूटर सिस्टम का एक बुनियादी घटक नहीं है?",
            options: [
              { text: "सीपीयू", isCorrect: false, rationale: "सीपीयू एक मुख्य घटक है।" },
              { text: "मेमोरी", isCorrect: false, rationale: "कंप्यूटर के कार्य करने के लिए मेमोरी आवश्यक है।" },
              { text: "इंटरनेट कनेक्शन", isCorrect: true, rationale: "एक कंप्यूटर इंटरनेट कनेक्शन के बिना भी काम कर सकता है।" },
              { text: "भंडारण", isCorrect: false, rationale: "भंडारण एक मौलिक घटक है।" },
            ],
            hint: "इनमें से कौन सा कंप्यूटर को अपने आप काम करने के लिए आवश्यक नहीं है?",
          },
          {
            id: "q29",
            question: "कंप्यूटर हार्डवेयर क्या है?",
            options: [
              { text: "कंप्यूटर पर प्रोग्राम और एप्लिकेशन।", isCorrect: false, rationale: "यह सॉफ्टवेयर है।" },
              { text: "कंप्यूटर के भौतिक भाग।", isCorrect: true, rationale: "हार्डवेयर में वे सभी भौतिक घटक शामिल होते हैं जिन्हें आप छू सकते हैं।" },
              { text: "कंप्यूटर पर संग्रहीत डेटा।", isCorrect: false, rationale: "यह डेटा है, हार्डवेयर नहीं।" },
              { text: "इंटरनेट कनेक्शन।", isCorrect: false, rationale: "यह एक सेवा है, कंप्यूटर का भौतिक हिस्सा नहीं।" },
            ],
            hint: "आप कंप्यूटर पर भौतिक रूप से क्या छू सकते हैं?",
          },
          {
            id: "q30",
            question: "बैंक कंप्यूटर का उपयोग कैसे करते हैं?",
            options: [
              { text: "ग्राहक खातों और लेनदेन का प्रबंधन करने के लिए।", isCorrect: true, rationale: "आधुनिक बैंकिंग कार्यों के लिए कंप्यूटर आवश्यक हैं।" },
              { text: "रोटी पकाने के लिए।", isCorrect: false, rationale: "यह बैंक में कंप्यूटर का कार्य नहीं है।" },
              { text: "हवाई जहाज उड़ाने के लिए।", isCorrect: false, rationale: "यह विमानन में कंप्यूटर का उपयोग है, बैंकिंग में नहीं।" },
              { text: "उपन्यास लिखने के लिए।", isCorrect: false, rationale: "यह लेखन में कंप्यूटर का उपयोग है, बैंकिंग में नहीं।" },
            ],
            hint: "एक बैंक आपके पैसे का हिसाब कैसे रखता है?",
          }
    ],
    },
  };