export const content = {
  en: {
    title: "Quiz 2: Computer Fundamentals",
    home: "Home",
    question: "Question",
    score: "Score",
    bestOfLuck: "Best of luck for your quiz!",
    startQuiz: "Start Quiz",
    nextQuestion: "Next Question",
    submit: "Submit",
    playAgain: "Play Again",
    quizComplete: "Quiz Complete!",
    showHint: "Show Hint",
    hideHint: "Hide Hint",
    welcomeMessage: "Welcome to the Computer Quiz! Enter your name to begin.",
    nameLabel: "Your Name",
    nameRequired: "Please enter your name to start the quiz.",
    timesUp: "Time's Up!",
    warningTitle: "Warning!",
    warningMessage: "You have left the quiz tab. This is not allowed. If you leave again, you will be disqualified.",
    warningUnderstand: "I Understand",
    disqualifiedTitle: "Disqualified!",
    disqualifiedMessage: "You have been disqualified for leaving the quiz tab multiple times.",
    showResults: "Show My Results",
    instructionsTitle: "Quiz Instructions",
    feature: "Feature",
    description: "Description",
    continue: "Continue",
    instructions: [
      { feature: "Timer", description: "The quiz has a time limit of 18 minutes. The timer will continue even if you switch tabs." },
      { feature: "Scoring", description: "Each correct answer is worth 1 point. Each incorrect answer will result in a deduction of 0.5 points." },
      { feature: "Question Grid", description: "Use the grid on the right to navigate to any question. The color of the number indicates its status:\n- Green: Answered\n- Yellow: Marked for Review\n- White: Skipped\n- Default: Unseen" },
      { feature: "Answer Selection", description: "Click on an option to select it. Your choice will be highlighted in purple. You can change your answer at any time before submitting." },
      { feature: "Next/Skip Button", description: "This button's text changes based on your action. If you haven't selected an answer, it says 'Skip'. If you have selected an answer, it says 'Next Question'. Clicking it always moves you to the next question." },
      { feature: "Review Button", description: "This button is enabled only after you select an answer. Use it to mark a question for later review." },
      { feature: "Hint Button", description: "If you are stuck, use the hint button to get a clue. Be careful, as hints may not always be available!" },
      { feature: "Language Toggle", description: "You can switch the quiz language between English and Hindi at any time using the buttons at the top right." },
      { feature: "Tab Switching", description: "You will receive one warning if you switch tabs. If you switch tabs a second time, you will be disqualified." },
      { feature: "Submission", description: "The 'Submit' button will appear on the last question and will only be enabled once all questions have been attempted (answered or marked for review)." },
      { feature: "Results", description: "After submitting, you will see your final score and grade based on your answers." }
    ],
    results: {
      failed: "Failed",
      passed: "Passed",
      c_grade: "Grade: C",
      b_grade: "Grade: B",
      a_grade: "Grade: A",
      excellent: "Excellent!",
      failedMessage: "Don't worry, {studentName}. Every expert was once a beginner. Keep trying!",
      passedMessage: "Good job, {studentName}! You've passed the quiz.",
      c_gradeMessage: "Nice work, {studentName}! You're getting the hang of it.",
      b_gradeMessage: "Great job, {studentName}! You have a solid understanding.",
      a_gradeMessage: "Excellent work, {studentName}! You're a star!",
      excellentMessage: "Outstanding, {studentName}! You're a computer whiz!",
    },
    quizData: [
      {
        id: "q1",
        question: "What are devices that let us interact with the computer, like a keyboard and mouse, called?",
        options: [
          { text: "Peripherals", isCorrect: true },
          { text: "Tertiary Storage", isCorrect: false },
          { text: "RAM", isCorrect: false },
          { text: "CPU", isCorrect: false },
        ],
        hint: "These devices are essential for input and output.",
      },
      {
        id: "q2",
        question: "Which type of storage is used for long-term backups and archival purposes?",
        options: [
          { text: "Primary Storage", isCorrect: false },
          { text: "Secondary Storage", isCorrect: false },
          { text: "Tertiary Storage", isCorrect: true },
          { text: "Cache Memory", isCorrect: false },
        ],
        hint: "Think about storage that is not accessed frequently.",
      },
      {
        id: "q3",
        question: "What is the main difference between RAM and ROM?",
        options: [
          { text: "RAM is volatile, while ROM is non-volatile.", isCorrect: true },
          { text: "ROM is faster than RAM.", isCorrect: false },
          { text: "RAM is used for long-term storage.", isCorrect: false },
          { text: "ROM is a type of secondary storage.", isCorrect: false },
        ],
        hint: "One retains data even when the power is off, and the other doesn't.",
      },
      {
        id: "q4",
        question: "Which unit is the largest measure of digital information?",
        options: [
          { text: "Kilobyte (KB)", isCorrect: false },
          { text: "Megabyte (MB)", isCorrect: false },
          { text: "Gigabyte (GB)", isCorrect: false },
          { text: "Terabyte (TB)", isCorrect: true },
        ],
        hint: "It's equivalent to 1,024 gigabytes.",
      },
      {
        id: "q5",
        question: "Which of the following allows devices to link with the CPU?",
        options: [
          { text: "Ports and Connectors", isCorrect: true },
          { text: "The motherboard", isCorrect: false },
          { text: "The power supply", isCorrect: false },
          { text: "The cooling fan", isCorrect: false },
        ],
        hint: "These are physical points of connection on a computer.",
      },
      {
        id: "q6",
        question: "What is considered the earliest form of mechanical computer?",
        options: [
          { text: "The abacus", isCorrect: true },
          { text: "The ENIAC", isCorrect: false },
          { text: "The personal computer", isCorrect: false },
          { text: "The mainframe", isCorrect: false },
        ],
        hint: "This early computing device dates back to ancient times.",
      },
      {
        id: "q7",
        question: "Which type of computer is the most powerful and used for complex scientific calculations?",
        options: [
          { text: "Personal Computer", isCorrect: false },
          { text: "Mainframe", isCorrect: false },
          { text: "Supercomputer", isCorrect: true },
          { text: "Minicomputer", isCorrect: false },
        ],
        hint: "These computers are at the forefront of processing capacity.",
      },
      {
        id: "q8",
        question: "Which peripheral is used to input sound into a computer?",
        options: [
          { text: "Monitor", isCorrect: false },
          { text: "Printer", isCorrect: false },
          { text: "Microphone", isCorrect: true },
          { text: "Speakers", isCorrect: false },
        ],
        hint: "This device captures your voice.",
      },
      {
        id: "q9",
        question: "Magnetic tapes are an example of which type of storage?",
        options: [
          { text: "Primary Storage", isCorrect: false },
          { text: "Secondary Storage", isCorrect: false },
          { text: "Tertiary Storage", isCorrect: true },
          { text: "Cache", isCorrect: false },
        ],
        hint: "This type of storage is often used for archiving large amounts of data.",
      },
      {
        id: "q10",
        question: "What does SSD stand for?",
        options: [
          { text: "Solid State Drive", isCorrect: true },
          { text: "Solid Storage Device", isCorrect: false },
          { text: "Super Speed Drive", isCorrect: false },
          { text: "Static State Drive", isCorrect: false },
        ],
        hint: "It's a modern, faster alternative to a traditional hard disk drive.",
      },
      {
        id: "q11",
        question: "Which type of memory is used to store the computer's boot-up instructions?",
        options: [
          { text: "RAM", isCorrect: false },
          { text: "ROM", isCorrect: true },
          { text: "SSD", isCorrect: false },
          { text: "HDD", isCorrect: false },
        ],
        hint: "This memory is non-volatile and contains firmware.",
      },
      {
        id: "q12",
        question: "Which of the following memory types is generally the fastest?",
        options: [
          { text: "RAM", isCorrect: false },
          { text: "SSD", isCorrect: false },
          { text: "HDD", isCorrect: false },
          { text: "CPU Cache", isCorrect: true },
        ],
        hint: "This memory is located directly on or very close to the CPU.",
      },
      {
        id: "q13",
        question: "How many megabytes are in one gigabyte?",
        options: [
          { text: "1000", isCorrect: false },
          { text: "1024", isCorrect: true },
          { text: "100", isCorrect: false },
          { text: "2048", isCorrect: false },
        ],
        hint: "The binary system uses powers of 2.",
      },
      {
        id: "q14",
        question: "What type of port is commonly used to connect a monitor to a computer?",
        options: [
          { text: "USB", isCorrect: false },
          { text: "HDMI", isCorrect: true },
          { text: "Ethernet", isCorrect: false },
          { text: "Audio Jack", isCorrect: false },
        ],
        hint: "It stands for High-Definition Multimedia Interface.",
      },
      {
        id: "q15",
        question: "Who is considered the 'Father of the Computer'?",
        options: [
          { text: "Alan Turing", isCorrect: false },
          { text: "Charles Babbage", isCorrect: true },
          { text: "Bill Gates", isCorrect: false },
          { text: "Steve Jobs", isCorrect: false },
        ],
        hint: "He designed the Analytical Engine.",
      },
      {
        id: "q16",
        question: "A laptop is an example of which type of computer?",
        options: [
          { text: "Supercomputer", isCorrect: false },
          { text: "Mainframe", isCorrect: false },
          { text: "Minicomputer", isCorrect: false },
          { text: "Personal Computer", isCorrect: true },
        ],
        hint: "It's designed for individual use.",
      },
      {
        id: "q17",
        question: "A joystick is primarily used for what purpose?",
        options: [
          { text: "Typing text", isCorrect: false },
          { text: "Printing documents", isCorrect: false },
          { text: "Gaming", isCorrect: true },
          { text: "Scanning images", isCorrect: false },
        ],
        hint: "It allows for directional and button-based input in interactive entertainment.",
      },
      {
        id: "q18",
        question: "In the memory hierarchy, which type of memory is the most expensive per byte?",
        options: [
          { text: "HDD", isCorrect: false },
          { text: "SSD", isCorrect: false },
          { text: "RAM", isCorrect: false },
          { text: "CPU Registers", isCorrect: true },
        ],
        hint: "The closer the memory is to the CPU, the more expensive it tends to be.",
      },
      {
        id: "q19",
        question: "What does USB stand for?",
        options: [
          { text: "Universal Serial Bus", isCorrect: true },
          { text: "Universal System Bus", isCorrect: false },
          { text: "Unified Serial Bus", isCorrect: false },
          { text: "Universal Signal Bus", isCorrect: false },
        ],
        hint: "It's a very common standard for connecting peripherals.",
      },
      {
        id: "q20",
        question: "What was the first commercially successful personal computer?",
        options: [
          { text: "IBM PC", isCorrect: false },
          { text: "Apple II", isCorrect: true },
          { text: "Commodore PET", isCorrect: false },
          { text: "Altair 8800", isCorrect: false },
        ],
        hint: "It was released in 1977 and was known for its color graphics.",
      },
      {
        id: "q21",
        question: "Which type of computer is typically used by large organizations for critical applications like bulk data processing?",
        options: [
          { text: "Supercomputer", isCorrect: false },
          { text: "Mainframe", isCorrect: true },
          { text: "Minicomputer", isCorrect: false },
          { text: "Personal Computer", isCorrect: false },
        ],
        hint: "They are known for their high reliability and transaction processing capabilities.",
      },
      {
        id: "q22",
        question: "What is the smallest unit of digital information?",
        options: [
          { text: "Byte", isCorrect: false },
          { text: "Bit", isCorrect: true },
          { text: "Kilobyte", isCorrect: false },
          { text: "Nibble", isCorrect: false },
        ],
        hint: "It can have a value of either 0 or 1.",
      },
      {
        id: "q23",
        question: "If you are working on a document and the power suddenly goes out, the contents of which memory type will be lost?",
        options: [
          { text: "ROM", isCorrect: false },
          { text: "RAM", isCorrect: true },
          { text: "SSD", isCorrect: false },
          { text: "Flash Memory", isCorrect: false },
        ],
        hint: "This memory is volatile, meaning it requires power to maintain the stored information.",
      },
      {
        id: "q24",
        question: "Cloud storage is a model of data storage in which the digital data is stored in...?",
        options: [
          { text: "Your computer's hard drive", isCorrect: false },
          { text: "A server owned by you", isCorrect: false },
          { text: "Logical pools of physical servers", isCorrect: true },
          { text: "A single, large hard drive in the sky", isCorrect: false },
        ],
        hint: "This involves a network of data centers.",
      },
      {
        id: "q25",
        question: "Which device is used to produce a physical copy of a digital document?",
        options: [
          { text: "Scanner", isCorrect: false },
          { text: "Monitor", isCorrect: false },
          { text: "Printer", isCorrect: true },
          { text: "Projector", isCorrect: false },
        ],
        hint: "It transfers text and images onto paper.",
      },
      {
        id: "q26",
        question: "The first generation of computers used what for circuitry?",
        options: [
          { text: "Transistors", isCorrect: false },
          { text: "Integrated Circuits", isCorrect: false },
          { text: "Microprocessors", isCorrect: false },
          { text: "Vacuum Tubes", isCorrect: true },
        ],
        hint: "These were large, generated a lot of heat, and were unreliable.",
      },
      {
        id: "q27",
        question: "What is a computer that is embedded into another device, such as a car or a microwave, called?",
        options: [
          { text: "Embedded System", isCorrect: true },
          { text: "Supercomputer", isCorrect: false },
          { text: "Mainframe", isCorrect: false },
          { text: "Workstation", isCorrect: false },
        ],
        hint: "It's designed for a specific function within a larger system.",
      },
      {
        id: "q28",
        question: "Which statement is true when comparing SSD and HDD?",
        options: [
          { text: "HDDs are faster than SSDs", isCorrect: false },
          { text: "SSDs have more moving parts than HDDs", isCorrect: false },
          { text: "SSDs are more durable than HDDs", isCorrect: true },
          { text: "HDDs are more expensive per gigabyte than SSDs", isCorrect: false },
        ],
        hint: "One uses flash memory and has no moving parts.",
      },
      {
        id: "q29",
        question: "An Ethernet port is used for what purpose?",
        options: [
          { text: "Connecting to a monitor", isCorrect: false },
          { text: "Connecting to a wired network", isCorrect: true },
          { text: "Charging a device", isCorrect: false },
          { text: "Connecting headphones", isCorrect: false },
        ],
        hint: "It's how you connect to the internet with a cable.",
      },
      {
        id: "q30",
        question: "Can the user easily write data to ROM?",
        options: [
          { text: "Yes, it is as easy as writing to RAM", isCorrect: false },
          { text: "No, ROM is read-only or requires a special process to write to", isCorrect: true },
          { text: "Yes, but it is much slower than RAM", isCorrect: false },
          { text: "No, ROM can only store numbers", isCorrect: false },
        ],
        hint: "The 'RO' in ROM stands for 'Read-Only'.",
      },
    ],
  },
  hi: {
    title: "प्रश्नोत्तरी 2: कंप्यूटर की मूल बातें",
    home: "होम",
    question: "प्रश्न",
    score: "स्कोर",
    bestOfLuck: "क्विज़ के लिए शुभकामनाएँ!",
    startQuiz: "क्विज़ शुरू करें",
    nextQuestion: "अगला प्रश्न",
    submit: "सबमिट करें",
    playAgain: "फिर से खेलें",
    quizComplete: "क्विज़ पूरा हुआ!",
    showHint: "संकेत दिखाएँ",
    hideHint: "संकेत छिपाएँ",
    welcomeMessage: "कंप्यूटर क्विज़ में आपका स्वागत है! शुरू करने के लिए अपना नाम दर्ज करें।",
    nameLabel: "आपका नाम",
    nameRequired: "क्विज़ शुरू करने के लिए कृपया अपना नाम दर्ज करें।",
    timesUp: "समय समाप्त!",
    warningTitle: "चेतावनी!",
    warningMessage: "आपने क्विज़ टैब छोड़ दिया है। इसकी अनुमति नहीं है। यदि आप फिर से छोड़ते हैं, तो आपको अयोग्य घोषित कर दिया जाएगा।",
    warningUnderstand: "मैं समझ गया",
    disqualifiedTitle: "अयोग्य!",
    disqualifiedMessage: "क्विज़ टैब को कई बार छोड़ने के कारण आपको अयोग्य घोषित कर दिया गया है।",
    showResults: "मेरे परिणाम दिखाएँ",
    instructionsTitle: "प्रश्नोत्तरी के निर्देश",
    feature: "सुविधा",
    description: "विवरण",
    continue: "जारी रखें",
    instructions: [
        { feature: "टाइमर", description: "क्विज़ के लिए 18 मिनट की समय सीमा है। यदि आप टैब बदलते हैं, तब भी टाइमर चलता रहेगा।" },
        { feature: "स्कोरिंग", description: "हर सही जवाब पर 1 अंक मिलेगा। हर गलत जवाब पर 0.5 अंक काटे जाएंगे।" },
        { feature: "प्रश्न ग्रिड", description: "किसी भी प्रश्न पर जाने के लिए दाईं ओर दिए गए ग्रिड का उपयोग करें। नंबर का रंग उसकी स्थिति बताता है:\n- हरा: उत्तर दिया हुआ\n- पीला: समीक्षा के लिए चिह्नित\n- सफ़ेद: छोड़ा हुआ\n- डिफ़ॉल्ट: नहीं देखा गया" },
        { feature: "उत्तर चुनना", description: "विकल्प चुनने के लिए उस पर क्लिक करें। आपकी पसंद बैंगनी रंग में हाइलाइट हो जाएगी। आप सबमिट करने से पहले कभी भी अपना जवाब बदल सकते हैं।" },
        { feature: "अगला/स्किप बटन", description: "यह बटन आपके एक्शन के आधार पर बदलता है। यदि आपने कोई उत्तर नहीं चुना है, तो यह 'स्किप' दिखाएगा। यदि आपने उत्तर चुन लिया है, तो यह 'अगला प्रश्न' दिखाएगा। इसे क्लिक करने पर आप हमेशा अगले प्रश्न पर जाते हैं।" },
        { feature: "रिव्यू बटन", description: "यह बटन केवल तभी काम करेगा जब आप कोई उत्तर चुनेंगे। इसका उपयोग किसी प्रश्न को बाद में देखने के लिए चिह्नित करने के लिए करें।" },
        { feature: "संकेत बटन", description: "यदि आप किसी प्रश्न में अटक जाते हैं, तो मदद के लिए संकेत बटन का उपयोग करें। ध्यान दें, संकेत हमेशा उपलब्ध नहीं हो सकते हैं!" },
        { feature: "भाषा बदलें", description: "आप ऊपर दाईं ओर दिए गए बटनों का उपयोग करके किसी भी समय क्विज़ की भाषा अंग्रेजी और हिंदी के बीच बदल सकते हैं।" },
        { feature: "टैब बदलना", description: "यदि आप क्विज़ टैब से बाहर जाते हैं तो आपको एक चेतावनी मिलेगी। दूसरी बार ऐसा करने पर आपको क्विज़ से बाहर कर दिया जाएगा।" },
        { feature: "सबमिट करना", description: "अंतिम प्रश्न पर 'सबमिट' बटन दिखाई देगा और यह तभी सक्रिय होगा जब आप सभी प्रश्नों का प्रयास कर लेंगे (उत्तर दिया हो या समीक्षा के लिए चिह्नित किया हो)।" },
        { feature: "परिणाम", description: "सबमिट करने के बाद, आपको आपके उत्तरों के आधार पर आपका अंतिम स्कोर और ग्रेड दिखाई देगा।" }
    ],
    results: {
      failed: "असफल",
      passed: "उत्तीर्ण",
      c_grade: "ग्रेड: C",
      b_grade: "ग्रेड: B",
      a_grade: "ग्रेड: A",
      excellent: "बहुत बढ़िया!",
      failedMessage: "चिंता न करें, {studentName}। हर विशेषज्ञ कभी नौसिखिया ही था। प्रयास करते रहें!",
      passedMessage: "बहुत अच्छा, {studentName}! आपने क्विज़ पास कर लिया है।",
      c_gradeMessage: "बहुत अच्छा, {studentName}! आप इसे समझने लगे हैं।",
      b_gradeMessage: "बहुत बढ़िया, {studentName}! आपकी समझ काफ़ी अच्छी है।",
      a_gradeMessage: "उत्कृष्ट, {studentName}! आप तो सितारे हैं!",
      excellentMessage: "असाधारण, {studentName}! आप तो कंप्यूटर के विशेषज्ञ हैं!",
    },
    quizData: [
      {
        id: "q1",
        question: "वे उपकरण क्या कहलाते हैं जो हमें कंप्यूटर के साथ इंटरैक्ट करने देते हैं, जैसे कीबोर्ड और माउस?",
        options: [
          { text: "पेरिफेरल्स", isCorrect: true },
          { text: "तृतीयक संग्रहण", isCorrect: false },
          { text: "रैम", isCorrect: false },
          { text: "सीपीयू", isCorrect: false },
        ],
        hint: "ये उपकरण इनपुट और आउटपुट के लिए आवश्यक हैं।",
      },
      {
        id: "q2",
        question: "किस प्रकार के संग्रहण का उपयोग दीर्घकालिक बैकअप और अभिलेखीय उद्देश्यों के लिए किया जाता है?",
        options: [
          { text: "प्राथमिक संग्रहण", isCorrect: false },
          { text: "माध्यमिक संग्रहण", isCorrect: false },
          { text: "तृतीयक संग्रहण", isCorrect: true },
          { text: "कैश मेमोरी", isCorrect: false },
        ],
        hint: "ऐसे संग्रहण के बारे में सोचें जिसे बार-बार एक्सेस नहीं किया जाता है।",
      },
      {
        id: "q3",
        question: "रैम और रोम के बीच मुख्य अंतर क्या है?",
        options: [
          { text: "रैम अस्थिर है, जबकि रोम गैर-अस्थिर है।", isCorrect: true },
          { text: "रोम रैम से तेज है।", isCorrect: false },
          { text: "रैम का उपयोग दीर्घकालिक संग्रहण के लिए किया जाता है।", isCorrect: false },
          { text: "रोम एक प्रकार का माध्यमिक संग्रहण है।", isCorrect: false },
        ],
        hint: "एक बिजली बंद होने पर भी डेटा बनाए रखता है, और दूसरा नहीं।",
      },
      {
        id: "q4",
        question: "डिजिटल जानकारी का सबसे बड़ा माप कौन सी इकाई है?",
        options: [
          { text: "किलोबाइट (KB)", isCorrect: false },
          { text: "मेगाबाइट (MB)", isCorrect: false },
          { text: "गीगाबाइट (GB)", isCorrect: false },
          { text: "टेराबाइट (TB)", isCorrect: true },
        ],
        hint: "यह 1,024 गीगाबाइट के बराबर है।",
      },
      {
        id: "q5",
        question: "निम्नलिखित में से कौन उपकरणों को सीपीयू से जोड़ने की अनुमति देता है?",
        options: [
          { text: "पोर्ट और कनेक्टर", isCorrect: true },
          { text: "मदरबोर्ड", isCorrect: false },
          { text: "बिजली की आपूर्ति", isCorrect: false },
          { text: "कूलिंग फैन", isCorrect: false },
        ],
        hint: "ये कंप्यूटर पर कनेक्शन के भौतिक बिंदु हैं।",
      },
      {
        id: "q6",
        question: "यांत्रिक कंप्यूटर का सबसे पहला रूप किसे माना जाता है?",
        options: [
          { text: "अबैकस", isCorrect: true },
          { text: "ENIAC", isCorrect: false },
          { text: "पर्सनल कंप्यूटर", isCorrect: false },
          { text: "मेनफ्रेम", isCorrect: false },
        ],
        hint: "यह प्रारंभिक कंप्यूटिंग डिवाइस प्राचीन काल का है।",
      },
      {
        id: "q7",
        question: "किस प्रकार का कंप्यूटर सबसे शक्तिशाली है और जटिल वैज्ञानिक गणनाओं के लिए उपयोग किया जाता है?",
        options: [
          { text: "पर्सनल कंप्यूटर", isCorrect: false },
          { text: "मेनफ्रेम", isCorrect: false },
          { text: "सुपर कंप्यूटर", isCorrect: true },
          { text: "मिनीकंप्यूटर", isCorrect: false },
        ],
        hint: "ये कंप्यूटर प्रसंस्करण क्षमता में सबसे आगे हैं।",
      },
      {
        id: "q8",
        question: "कंप्यूटर में ध्वनि इनपुट करने के लिए किस पेरिफेरल का उपयोग किया जाता है?",
        options: [
          { text: "मॉनिटर", isCorrect: false },
          { text: "प्रिंटर", isCorrect: false },
          { text: "माइक्रोफोन", isCorrect: true },
          { text: "स्पीकर", isCorrect: false },
        ],
        hint: "यह डिवाइस आपकी आवाज को कैप्चर करता है।",
      },
      {
        id: "q9",
        question: "चुंबकीय टेप किस प्रकार के भंडारण का एक उदाहरण है?",
        options: [
          { text: "प्राथमिक भंडारण", isCorrect: false },
          { text: "माध्यमिक भंडारण", isCorrect: false },
          { text: "तृतीयक भंडारण", isCorrect: true },
          { text: "कैश", isCorrect: false },
        ],
        hint: "इस प्रकार के भंडारण का उपयोग अक्सर बड़ी मात्रा में डेटा संग्रहीत करने के लिए किया जाता है।",
      },
      {
        id: "q10",
        question: "SSD का पूरा नाम क्या है?",
        options: [
          { text: "सॉलिड स्टेट ड्राइव", isCorrect: true },
          { text: "सॉलिड स्टोरेज डिवाइस", isCorrect: false },
          { text: "सुपर स्पीड ड्राइव", isCorrect: false },
          { text: "स्टेटिक स्टेट ड्राइव", isCorrect: false },
        ],
        hint: "यह पारंपरिक हार्ड डिस्क ड्राइव का एक आधुनिक, तेज़ विकल्प है।",
      },
      {
        id: "q11",
        question: "कंप्यूटर के बूट-अप निर्देशों को संग्रहीत करने के लिए किस प्रकार की मेमोरी का उपयोग किया जाता है?",
        options: [
          { text: "रैम", isCorrect: false },
          { text: "रोम", isCorrect: true },
          { text: "एसएसडी", isCorrect: false },
          { text: "एचडीडी", isCorrect: false },
        ],
        hint: "यह मेमोरी गैर-वाष्पशील है और इसमें फर्मवेयर होता है।",
      },
      {
        id: "q12",
        question: "निम्नलिखित में से कौन सा मेमोरी प्रकार आम तौर पर सबसे तेज़ है?",
        options: [
          { text: "रैम", isCorrect: false },
          { text: "एसएसडी", isCorrect: false },
          { text: "एचडीडी", isCorrect: false },
          { text: "सीपीयू कैश", isCorrect: true },
        ],
        hint: "यह मेमोरी सीधे सीपीयू पर या उसके बहुत करीब स्थित होती है।",
      },
      {
        id: "q13",
        question: "एक गीगाबाइट में कितने मेगाबाइट होते हैं?",
        options: [
          { text: "1000", isCorrect: false },
          { text: "1024", isCorrect: true },
          { text: "100", isCorrect: false },
          { text: "2048", isCorrect: false },
        ],
        hint: "बाइनरी सिस्टम 2 की शक्तियों का उपयोग करता है।",
      },
      {
        id: "q14",
        question: "एक मॉनिटर को कंप्यूटर से जोड़ने के लिए आमतौर पर किस प्रकार के पोर्ट का उपयोग किया जाता है?",
        options: [
          { text: "यूएसबी", isCorrect: false },
          { text: "एचडीएमआई", isCorrect: true },
          { text: "ईथरनेट", isCorrect: false },
          { text: "ऑडियो जैक", isCorrect: false },
        ],
        hint: "इसका पूरा नाम हाई-डेफिनिशन मल्टीमीडिया इंटरफेस है।",
      },
      {
        id: "q15",
        question: "'कंप्यूटर का जनक' किसे माना जाता है?",
        options: [
          { text: "एलन ट्यूरिंग", isCorrect: false },
          { text: "चार्ल्स बैबेज", isCorrect: true },
          { text: "बिल गेट्स", isCorrect: false },
          { text: "स्टीव जॉब्स", isCorrect: false },
        ],
        hint: "उन्होंने एनालिटिकल इंजन डिजाइन किया था।",
      },
      {
        id: "q16",
        question: "एक लैपटॉप किस प्रकार के कंप्यूटर का उदाहरण है?",
        options: [
          { text: "सुपर कंप्यूटर", isCorrect: false },
          { text: "मेनफ्रेम", isCorrect: false },
          { text: "मिनीकंप्यूटर", isCorrect: false },
          { text: "पर्सनल कंप्यूटर", isCorrect: true },
        ],
        hint: "यह व्यक्तिगत उपयोग के लिए डिज़ाइन किया गया है।",
      },
      {
        id: "q17",
        question: "एक जॉयस्टिक का उपयोग मुख्य रूप से किस उद्देश्य के लिए किया जाता है?",
        options: [
          { text: "टेक्स्ट टाइप करना", isCorrect: false },
          { text: "दस्तावेज़ प्रिंट करना", isCorrect: false },
          { text: "गेमिंग", isCorrect: true },
          { text: "छवियों को स्कैन करना", isCorrect: false },
        ],
        hint: "यह इंटरैक्टिव मनोरंजन में दिशात्मक और बटन-आधारित इनपुट की अनुमति देता है।",
      },
      {
        id: "q18",
        question: "मेमोरी पदानुक्रम में, प्रति बाइट कौन सी मेमोरी सबसे महंगी है?",
        options: [
          { text: "एचडीडी", isCorrect: false },
          { text: "एसएसडी", isCorrect: false },
          { text: "रैम", isCorrect: false },
          { text: "सीपीयू रजिस्टर", isCorrect: true },
        ],
        hint: "मेमोरी सीपीयू के जितनी करीब होती है, उतनी ही महंगी होती है।",
      },
      {
        id: "q19",
        question: "USB का पूरा नाम क्या है?",
        options: [
          { text: "यूनिवर्सल सीरियल बस", isCorrect: true },
          { text: "यूनिवर्सल सिस्टम बस", isCorrect: false },
          { text: "यूनिफाइड सीरियल बस", isCorrect: false },
          { text: "यूनिवर्सल सिग्नल बस", isCorrect: false },
        ],
        hint: "यह पेरिफेरल्स को जोड़ने के लिए एक बहुत ही सामान्य मानक है।",
      },
      {
        id: "q20",
        question: "पहला व्यावसायिक रूप से सफल पर्सनल कंप्यूटर कौन सा था?",
        options: [
          { text: "आईबीएम पीसी", isCorrect: false },
          { text: "एप्पल II", isCorrect: true },
          { text: "कमोडोर पीईटी", isCorrect: false },
          { text: "अल्टेयर 8800", isCorrect: false },
        ],
        hint: "यह 1977 में जारी किया गया था और अपने रंगीन ग्राफिक्स के लिए जाना जाता था।",
      },
      {
        id: "q21",
        question: "बड़े संगठन आमतौर पर बल्क डेटा प्रोसेसिंग जैसे महत्वपूर्ण अनुप्रयोगों के लिए किस प्रकार के कंप्यूटर का उपयोग करते हैं?",
        options: [
          { text: "सुपर कंप्यूटर", isCorrect: false },
          { text: "मेनफ्रेम", isCorrect: true },
          { text: "मिनीकंप्यूटर", isCorrect: false },
          { text: "पर्सनल कंप्यूटर", isCorrect: false },
        ],
        hint: "वे अपनी उच्च विश्वसनीयता और लेनदेन प्रसंस्करण क्षमताओं के लिए जाने जाते हैं।",
      },
      {
        id: "q22",
        question: "डिजिटल जानकारी की सबसे छोटी इकाई क्या है?",
        options: [
          { text: "बाइट", isCorrect: false },
          { text: "बिट", isCorrect: true },
          { text: "किलोबाइट", isCorrect: false },
          { text: "निबल", isCorrect: false },
        ],
        hint: "इसका मान 0 या 1 हो सकता है।",
      },
      {
        id: "q23",
        question: "यदि आप एक दस्तावेज़ पर काम कर रहे हैं और अचानक बिजली चली जाती है, तो किस प्रकार की मेमोरी की सामग्री खो जाएगी?",
        options: [
          { text: "रोम", isCorrect: false },
          { text: "रैम", isCorrect: true },
          { text: "एसएसडी", isCorrect: false },
          { text: "फ्लैश मेमोरी", isCorrect: false },
        ],
        hint: "यह मेमोरी अस्थिर है, जिसका अर्थ है कि संग्रहीत जानकारी को बनाए रखने के लिए इसे शक्ति की आवश्यकता होती है।",
      },
      {
        id: "q24",
        question: "क्लाउड स्टोरेज डेटा स्टोरेज का एक मॉडल है जिसमें डिजिटल डेटा कहाँ संग्रहीत होता है?",
        options: [
          { text: "आपके कंप्यूटर की हार्ड ड्राइव", isCorrect: false },
          { text: "आपके स्वामित्व वाला एक सर्वर", isCorrect: false },
          { text: "भौतिक सर्वरों के तार्किक पूल", isCorrect: true },
          { text: "आसमान में एक एकल, बड़ी हार्ड ड्राइव", isCorrect: false },
        ],
        hint: "इसमें डेटा केंद्रों का एक नेटवर्क शामिल है।",
      },
      {
        id: "q25",
        question: "डिजिटल दस्तावेज़ की भौतिक प्रतिलिपि बनाने के लिए किस उपकरण का उपयोग किया जाता है?",
        options: [
          { text: "स्कैनर", isCorrect: false },
          { text: "मॉनिटर", isCorrect: false },
          { text: "प्रिंटर", isCorrect: true },
          { text: "प्रोजेक्टर", isCorrect: false },
        ],
        hint: "यह टेक्स्ट और छवियों को कागज पर स्थानांतरित करता है।",
      },
      {
        id: "q26",
        question: "कंप्यूटर की पहली पीढ़ी ने सर्किटरी के लिए किसका उपयोग किया?",
        options: [
          { text: "ट्रांजिस्टर", isCorrect: false },
          { text: "एकीकृत सर्किट", isCorrect: false },
          { text: "माइक्रोप्रोसेसर", isCorrect: false },
          { text: "वैक्यूम ट्यूब", isCorrect: true },
        ],
        hint: "ये बड़े थे, बहुत अधिक गर्मी उत्पन्न करते थे, और अविश्वसनीय थे।",
      },
      {
        id: "q27",
        question: "एक कंप्यूटर जो किसी अन्य डिवाइस, जैसे कार या माइक्रोवेव, में एम्बेडेड होता है, उसे क्या कहा जाता है?",
        options: [
          { text: "एम्बेडेड सिस्टम", isCorrect: true },
          { text: "सुपर कंप्यूटर", isCorrect: false },
          { text: "मेनफ्रेम", isCorrect: false },
          { text: "वर्कस्टेशन", isCorrect: false },
        ],
        hint: "यह एक बड़ी प्रणाली के भीतर एक विशिष्ट कार्य के लिए डिज़ाइन किया गया है।",
      },
      {
        id: "q28",
        question: "SSD और HDD की तुलना करते समय कौन सा कथन सत्य है?",
        options: [
          { text: "HDD SSD से तेज होते हैं", isCorrect: false },
          { text: "SSD में HDD से अधिक चलने वाले हिस्से होते हैं", isCorrect: false },
          { text: "SSD HDD से अधिक टिकाऊ होते हैं", isCorrect: true },
          { text: "HDD SSD से प्रति गीगाबाइट अधिक महंगे होते हैं", isCorrect: false },
        ],
        hint: "एक फ्लैश मेमोरी का उपयोग करता है और इसमें कोई चलने वाला हिस्सा नहीं होता है।",
      },
      {
        id: "q29",
        question: "एक ईथरनेट पोर्ट का उपयोग किस उद्देश्य के लिए किया जाता है?",
        options: [
          { text: "एक मॉनिटर से कनेक्ट करना", isCorrect: false },
          { text: "एक वायर्ड नेटवर्क से कनेक्ट करना", isCorrect: true },
          { text: "एक डिवाइस चार्ज करना", isCorrect: false },
          { text: "हेडफ़ोन कनेक्ट करना", isCorrect: false },
        ],
        hint: "यह है कि आप एक केबल के साथ इंटरनेट से कैसे जुड़ते हैं।",
      },
      {
        id: "q30",
        question: "क्या उपयोगकर्ता आसानी से ROM में डेटा लिख सकता है?",
        options: [
          { text: "हाँ, यह रैम में लिखने जितना ही आसान है", isCorrect: false },
          { text: "नहीं, रोम केवल-पढ़ने के लिए है या लिखने के लिए एक विशेष प्रक्रिया की आवश्यकता होती है", isCorrect: true },
          { text: "हाँ, लेकिन यह रैम की तुलना में बहुत धीमा है", isCorrect: false },
          { text: "नहीं, रोम केवल संख्याएँ संग्रहीत कर सकता है", isCorrect: false },
        ],
        hint: "ROM में 'RO' का अर्थ 'केवल-पढ़ने' है।",
      },
    ],
  },
};